server:
  port: ${PORT:8001}
spring:
  application:
    name: app-payment-consumer
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}

logging:
  level:
    org:
      apache:
        kafka: INFO
    springframework:
      kafka:
        support:
          serializer: INFO